#############################################################################
# Makefile for building: FFEditor
# Generated by qmake (2.01a) (Qt 4.8.6) on: mar. nov. 18 17:43:25 2014
# Project:  FFEditor.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile FFEditor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Wno-write-strings -O2 -Wno-deprecated -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/qt4/Qt -I/usr/include/QGLViewer -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/X11R6/lib -L/usr/lib/i386-linux-gnu -L/usr/local/lib -lQGLViewer -L. -lGLU -lFFEditor -lGL -lQtXml -lQtOpenGL -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = wlMeshGeneratorStudents.cxx \
		mpiProject.cxx moc_mpiProject.cpp \
		moc_wlQGLViewer.cpp \
		moc_wlMesh.cpp \
		moc_wlMeshGenerator.cpp \
		moc_wlMeshGeneratorStudents.cpp \
		moc_wlPointEditor.cpp \
		moc_wlQtSliderSpinBox.cpp
OBJECTS       = wlMeshGeneratorStudents.o \
		mpiProject.o \
		moc_mpiProject.o \
		moc_wlQGLViewer.o \
		moc_wlMesh.o \
		moc_wlMeshGenerator.o \
		moc_wlMeshGeneratorStudents.o \
		moc_wlPointEditor.o \
		moc_wlQtSliderSpinBox.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		FFEditor.pro
QMAKE_TARGET  = FFEditor
DESTDIR       = 
TARGET        = FFEditor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FFEditor.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile FFEditor.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile FFEditor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/FFEditor1.0.0 || $(MKDIR) .tmp/FFEditor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FFEditor1.0.0/ && $(COPY_FILE) --parents mpiProject.h wlCore.h wlMacros.h wlQGLViewer.h wlMesh.h wlMeshGenerator.h wlMeshGeneratorStudents.h wlPointEditor.h wlQtSliderSpinBox.h .tmp/FFEditor1.0.0/ && $(COPY_FILE) --parents wlMeshGeneratorStudents.cxx mpiProject.cxx .tmp/FFEditor1.0.0/ && (cd `dirname .tmp/FFEditor1.0.0` && $(TAR) FFEditor1.0.0.tar FFEditor1.0.0 && $(COMPRESS) FFEditor1.0.0.tar) && $(MOVE) `dirname .tmp/FFEditor1.0.0`/FFEditor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FFEditor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

/usr/lib/i386-linux-gnu/qt4/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mpiProject.cpp moc_wlQGLViewer.cpp moc_wlMesh.cpp moc_wlMeshGenerator.cpp moc_wlMeshGeneratorStudents.cpp moc_wlPointEditor.cpp moc_wlQtSliderSpinBox.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mpiProject.cpp moc_wlQGLViewer.cpp moc_wlMesh.cpp moc_wlMeshGenerator.cpp moc_wlMeshGeneratorStudents.cpp moc_wlPointEditor.cpp moc_wlQtSliderSpinBox.cpp
moc_mpiProject.cpp: wlMacros.h \
		wlMesh.h \
		wlQGLViewer.h \
		wlCore.h \
		wlPointEditor.h \
		wlMeshGeneratorStudents.h \
		wlMeshGenerator.h \
		mpiProject.h \
		/usr/lib/i386-linux-gnu/qt4/bin/moc
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mpiProject.h -o moc_mpiProject.cpp

moc_wlQGLViewer.cpp: wlQGLViewer.h \
		/usr/lib/i386-linux-gnu/qt4/bin/moc
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) wlQGLViewer.h -o moc_wlQGLViewer.cpp

moc_wlMesh.cpp: wlQGLViewer.h \
		wlCore.h \
		wlMacros.h \
		wlMesh.h \
		/usr/lib/i386-linux-gnu/qt4/bin/moc
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) wlMesh.h -o moc_wlMesh.cpp

moc_wlMeshGenerator.cpp: wlCore.h \
		wlMacros.h \
		wlMeshGenerator.h \
		/usr/lib/i386-linux-gnu/qt4/bin/moc
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) wlMeshGenerator.h -o moc_wlMeshGenerator.cpp

moc_wlMeshGeneratorStudents.cpp: wlMeshGenerator.h \
		wlCore.h \
		wlMacros.h \
		wlMeshGeneratorStudents.h \
		/usr/lib/i386-linux-gnu/qt4/bin/moc
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) wlMeshGeneratorStudents.h -o moc_wlMeshGeneratorStudents.cpp

moc_wlPointEditor.cpp: wlCore.h \
		wlMacros.h \
		wlPointEditor.h \
		/usr/lib/i386-linux-gnu/qt4/bin/moc
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) wlPointEditor.h -o moc_wlPointEditor.cpp

moc_wlQtSliderSpinBox.cpp: wlCore.h \
		wlMacros.h \
		wlQtSliderSpinBox.h \
		/usr/lib/i386-linux-gnu/qt4/bin/moc
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) wlQtSliderSpinBox.h -o moc_wlQtSliderSpinBox.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

wlMeshGeneratorStudents.o: wlMeshGeneratorStudents.cxx wlMeshGeneratorStudents.h \
		wlMeshGenerator.h \
		wlCore.h \
		wlMacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wlMeshGeneratorStudents.o wlMeshGeneratorStudents.cxx

mpiProject.o: mpiProject.cxx mpiProject.h \
		wlMacros.h \
		wlMesh.h \
		wlQGLViewer.h \
		wlCore.h \
		wlPointEditor.h \
		wlMeshGeneratorStudents.h \
		wlMeshGenerator.h \
		wlQtSliderSpinBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpiProject.o mpiProject.cxx

moc_mpiProject.o: moc_mpiProject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpiProject.o moc_mpiProject.cpp

moc_wlQGLViewer.o: moc_wlQGLViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wlQGLViewer.o moc_wlQGLViewer.cpp

moc_wlMesh.o: moc_wlMesh.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wlMesh.o moc_wlMesh.cpp

moc_wlMeshGenerator.o: moc_wlMeshGenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wlMeshGenerator.o moc_wlMeshGenerator.cpp

moc_wlMeshGeneratorStudents.o: moc_wlMeshGeneratorStudents.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wlMeshGeneratorStudents.o moc_wlMeshGeneratorStudents.cpp

moc_wlPointEditor.o: moc_wlPointEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wlPointEditor.o moc_wlPointEditor.cpp

moc_wlQtSliderSpinBox.o: moc_wlQtSliderSpinBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wlQtSliderSpinBox.o moc_wlQtSliderSpinBox.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

